package db;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import beans.db.DBBean;
import beans.db.DBSynonym;

public class SynonymsHelper extends TableHelper {
	
	private static final String CREATE_TABLE =
		"CREATE TABLE SYNONYMS(" +
			"ID INTEGER GENERATED BY DEFAULT AS IDENTITY" +
				"(START WITH 1) NOT NULL PRIMARY KEY," +
			"WORD_REF INTEGER NOT NULL," +
			"SYNONYM_REF INTEGER NOT NULL," +
			"CONSTRAINT SYS_FK_WR FOREIGN KEY(WORD_REF) " +
				"REFERENCES WORDS(ID)," +
			"CONSTRAINT SYS_FK_SR FOREIGN KEY(SYNONYM_REF) " +
				"REFERENCES WORDS(ID))";
	
	private static final String INSERT = 
		"INSERT INTO SYNONYMS" +
			"(word_ref,synonym_ref) " +
		"VALUES (?,?)";
	
	private static final String UPDATE = 
		"UPDATE SYNONYMS" +
			"SET word_ref = ?, synonym_ref = ? " +
		"WHERE id = ?";
	
	private static final String GET_BY_ID = 
		"SELECT " +
			"id, " +
			"word_ref, " +
			"synonym_ref " +
		"FROM SYNONYMS " +
		"WHERE id = ?";

	private static final String GET_BY_WORD = 
		"SELECT " +
			"id, " +
			"word_ref, " +
			"synonym_ref " +
		"FROM SYNONYMS " +
		"WHERE word_ref = ?";
	
	private static SynonymsHelper instance;
	
	private SynonymsHelper(DatabaseManager db) {
		super(db);
	}
	
	public static SynonymsHelper getInstance(DatabaseManager db){
		if (instance == null)
			instance = new SynonymsHelper(db);
		
		return instance;
	}
	
    public int createTable() throws SQLException{
        return db.update(CREATE_TABLE);
    }
    
    @Override
	public int insert(DBBean bean) throws Exception{
    	int ret = 0;
    	if (bean!=null){
    		DBSynonym synonym = null;
    		try{
    			synonym = (DBSynonym)bean;
    		}catch (Exception e) {
				// TODO: handle exception
    			throw e;
			}
    		PreparedStatement ps = null;
    		try{
		    	ps = db.getPreparedStatement(INSERT);
		    	
		    	ps.setInt(1, synonym.getWordRef());
		    	ps.setInt(2, synonym.getSynonymRef());
		    	
		    	ret = ps.executeUpdate();
    		}catch (Exception e) {
				// TODO: handle exception
				throw e;
			}finally{
				if (ps != null)
					ps.close();
			}
    	}
    	
    	return ret;
	}

	@Override
	public int update(DBBean bean) throws Exception {
    	int ret = 0;
		if (bean!=null && bean.getId()!=0){
    		DBSynonym synonym = null;
    		try{
    			synonym = (DBSynonym)bean;
    		}catch (Exception e) {
				// TODO: handle exception
    			throw e;
			}
    		PreparedStatement ps = null;
    		try{
		    	ps = db.getPreparedStatement(UPDATE);
		    	
		    	ps.setInt(1, synonym.getWordRef());
		    	ps.setInt(2, synonym.getSynonymRef());
		    	ps.setInt(3, synonym.getId());
		    	
		    	ret = ps.executeUpdate();
    		}catch (Exception e) {
				// TODO: handle exception
				throw e;
			}finally{
				if (ps != null)
					ps.close();
			}
		}
		return ret;		
	}

	@Override
	public DBBean getById(int id) throws Exception {
		DBSynonym synonym = null;
		if (id != 0){   	
    		PreparedStatement ps = null;
    		try{
		    	ps = db.getPreparedStatement(GET_BY_ID);
		    	
		    	ps.setInt(1, id);
		    	
		    	ResultSet rs = ps.executeQuery(); 

		        if (rs.next()){
		        	synonym = new DBSynonym();
		        	synonym.setId(rs.getInt("id"));
		        	synonym.setWordRef(rs.getInt("word_ref"));
		        	synonym.setSynonymRef(rs.getInt("synonym_ref"));
		        }	

    		}catch (Exception e) {
				// TODO: handle exception
				throw e;
			}finally{
				if (ps != null)
					ps.close();
			}
		}
		return synonym;
	}

	public DBSynonym getByWord(int value) throws SQLException {
		DBSynonym synonym = null;
		if (value!=0){
	    	PreparedStatement ps = db.getPreparedStatement(GET_BY_WORD);
	    	
	    	ps.setInt(1, value);
	    	
	    	ResultSet rs = ps.executeQuery(); 

	        if (rs.next()){
	        	synonym = new DBSynonym();
	        	synonym.setId(rs.getInt("id"));
	        	synonym.setWordRef(rs.getInt("word_ref"));
	        	synonym.setSynonymRef(rs.getInt("synonym_ref"));
	        }	
		}
		
		return synonym;		
	}

}
